import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SITE_URL, SITE_NAME, SITE_TITLE, SITE_DESCRIPTION, SITE_KEYWORDS } from "@/lib/site";
import { StructuredData } from "@/components/structured-data";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  // metadataBase makes every relative URL below (canonical, OG image) absolute.
  // Without it, social crawlers get relative paths and drop the share preview.
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_TITLE,
    template: "%s · Foji AI",
  },
  description: SITE_DESCRIPTION,
  keywords: SITE_KEYWORDS,
  applicationName: SITE_NAME,
  authors: [{ name: "Foji AI" }],
  creator: "Foji AI",
  publisher: "Foji AI",
  alternates: { canonical: "/" },
  icons: {
    icon: "/favicon_foji.png",
    shortcut: "/favicon.ico",
    apple: "/favicon_foji.png",
  },
  openGraph: {
    type: "website",
    locale: "pt_BR",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: "Foji AI — Sua empresa no WhatsApp, com IA",
    description: SITE_DESCRIPTION,
    // The image is generated by app/opengraph-image.tsx and picked up here.
  },
  twitter: {
    card: "summary_large_image",
    title: "Foji AI — Sua empresa no WhatsApp, com IA",
    description: SITE_DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  category: "technology",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <body className="bg-background text-foreground font-sans overflow-x-hidden">
        <StructuredData />
        {children}
      </body>
    </html>
  );
}
